title: "the barthel laboratory"
description: "studying telomere dysfunction in gliomagenesis and evolution at TGen"
url: https://www.barthel-lab.com

logo: /images/logo.png

author:
  name: Floris Barthel
  twitter: fpbarthel
  linkedin: https://www.linkedin.com/in/florisbarthel/

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

last_modified_at: 2023-07-13

kramdown:
  parse_block_html: true

plugins:
  - jekyll-sitemap
  - jekyll-feed

feed:
  categories:
    - news

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"